name: conversation_maker
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  built_value: ^6.6.0
  built_collection: ^4.2.2
  equatable: ^0.2.6
  flare_flutter: ^1.5.0
  image_picker: ^0.6.0+17
  font_awesome_flutter: ^8.2.0
  path_provider: ^1.1.2
  intl: ^0.15.8
  image_cropper: ^1.0.2
  flutter_svg: ^0.13.1
  bubble_tab_indicator: ^0.1.4
  keyboard_visibility: ^0.5.6
  flutter_slidable: "^0.5.4"
  provider: ^3.1.0+1
  json_annotation: ^3.0.0
  sembast: ^2.1.0+1
  shared_preferences: ^0.5.4+5
  rxdart: ^0.22.6
  flutter_sequence_animation: ^3.0.1
  firebase_core: ^0.4.2+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.6.0
  mockito: ^4.1.0
  json_serializable: ^3.2.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #   To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg_map.jpg
    - assets/img_default_avatar.jpg
    - assets/img_avatar_default.png
    - assets/img_wave.png
    - assets/emoji/emoji_default.svg
    - assets/emoji/emoji_1.svg
    - assets/emoji/emoji_2.svg
    - assets/emoji/emoji_3.svg
    - assets/emoji/emoji_4.svg
    - assets/emoji/emoji_5.svg
    - assets/emoji/emoji_6.svg
    - assets/emoji/emoji_7.svg
    - assets/emoji/emoji_8.svg
    - assets/emoji/emoji_9.svg
    - assets/emoji/emoji_10.svg
    - assets/emoji/emoji_11.svg
    - assets/emoji/emoji_12.svg
    - assets/emoji/emoji_13.svg
    - assets/emoji/emoji_14.svg
    - assets/emoji/emoji_15.svg
    - assets/emoji/emoji_16.svg
    - assets/emoji/emoji_17.svg
    - assets/emoji/emoji_18.svg
    - assets/emoji/emoji_19.svg
    - assets/emoji/emoji_20.svg
    - assets/ic_camera.svg
    - assets/ic_four_dots.svg
    - assets/ic_microphone.svg
    - assets/ic_photo.svg
    - assets/ic_arrow_right.svg
    - assets/sticker/meep/tile000.png
    - assets/sticker/meep/tile001.png
    - assets/sticker/meep/tile002.png
    - assets/sticker/meep/tile003.png
    - assets/sticker/meep/tile004.png
    - assets/sticker/meep/tile005.png
    - assets/sticker/meep/tile006.png
    - assets/sticker/meep/tile007.png
    - assets/sticker/meep/tile008.png
    - assets/sticker/meep/tile009.png
    - assets/sticker/meep/tile010.png
    - assets/sticker/meep/tile011.png
    - assets/sticker/meep/tile012.png
    - assets/sticker/meep/tile013.png
    - assets/sticker/meep/tile014.png
    - assets/sticker/meep/tile015.png
    - assets/sticker/meep/tile016.png
    - assets/sticker/meep/tile017.png
    - assets/sticker/meep/tile018.png
    - assets/sticker/meep/tile019.png
    - assets/sticker/meep/tile020.png
    - assets/sticker/meep/tile021.png
    - assets/sticker/meep/tile022.png
    - assets/sticker/meep/tile023.png
    - assets/sticker/meep/tile024.png
    - assets/sticker/meep/tile025.png
    - assets/sticker/meep/tile026.png
    - assets/sticker/meep/tile027.png
    - assets/sticker/meep/tile028.png
    - assets/sticker/meep/tile029.png
    - assets/sticker/meep/tile030.png
    - assets/sticker/meep/tile031.png
    - assets/sticker/brown/tile000.png
    - assets/sticker/brown/tile001.png
    - assets/sticker/brown/tile002.png
    - assets/sticker/brown/tile003.png
    - assets/sticker/brown/tile004.png
    - assets/sticker/brown/tile005.png
    - assets/sticker/brown/tile006.png
    - assets/sticker/brown/tile007.png
    - assets/sticker/brown/tile008.png
    - assets/sticker/brown/tile009.png
    - assets/sticker/brown/tile010.png
    - assets/sticker/brown/tile011.png
    - assets/sticker/brown/tile012.png
    - assets/sticker/brown/tile013.png
    - assets/sticker/brown/tile014.png
    - assets/sticker/brown/tile015.png
    - assets/sticker/brown/tile016.png
    - assets/sticker/brown/tile017.png
    - assets/sticker/brown/tile018.png
    - assets/sticker/brown/tile019.png
    - assets/sticker/mimiandneko/tile000.png
    - assets/sticker/mimiandneko/tile001.png
    - assets/sticker/mimiandneko/tile002.png
    - assets/sticker/mimiandneko/tile003.png
    - assets/sticker/mimiandneko/tile004.png
    - assets/sticker/mimiandneko/tile005.png
    - assets/sticker/mimiandneko/tile006.png
    - assets/sticker/mimiandneko/tile007.png
    - assets/sticker/mimiandneko/tile008.png
    - assets/sticker/mimiandneko/tile009.png
    - assets/sticker/mimiandneko/tile010.png
    - assets/sticker/mimiandneko/tile011.png
    - assets/sticker/mimiandneko/tile012.png
    - assets/sticker/mimiandneko/tile013.png
    - assets/sticker/mimiandneko/tile014.png
    - assets/sticker/mimiandneko/tile015.png
    - assets/sticker/mimiandneko/tile016.png
    - assets/sticker/mimiandneko/tile017.png
    - assets/sticker/mimiandneko/tile018.png
    - assets/sticker/mimiandneko/tile019.png
    - assets/sticker/mimiandneko/tile020.png
    - assets/sticker/mimiandneko/tile021.png
    - assets/sticker/mimiandneko/tile022.png
    - assets/sticker/mimiandneko/tile023.png
    - assets/sticker/mugsy/tile000.png
    - assets/sticker/mugsy/tile001.png
    - assets/sticker/mugsy/tile002.png
    - assets/sticker/mugsy/tile003.png
    - assets/sticker/mugsy/tile004.png
    - assets/sticker/mugsy/tile005.png
    - assets/sticker/mugsy/tile006.png
    - assets/sticker/mugsy/tile007.png
    - assets/sticker/mugsy/tile008.png
    - assets/sticker/mugsy/tile009.png
    - assets/sticker/mugsy/tile010.png
    - assets/sticker/mugsy/tile011.png
    - assets/sticker/mugsy/tile012.png
    - assets/sticker/mugsy/tile013.png
    - assets/sticker/mugsy/tile014.png
    - assets/sticker/mugsy/tile015.png
    - assets/sticker/mugsy/tile016.png
    - assets/sticker/mugsy/tile017.png
    - assets/sticker/mugsy/tile018.png
    - assets/sticker/mugsy/tile019.png
    - assets/sticker/mugsy/tile020.png
    - assets/sticker/mugsy/tile021.png
    - assets/sticker/mugsy/tile022.png
    - assets/sticker/mugsy/tile023.png
    - assets/sticker/mugsy/tile024.png
    - assets/sticker/mugsy/tile025.png
    - assets/sticker/mugsy/tile026.png
    - assets/sticker/mugsy/tile027.png
    - assets/sticker/mugsy/tile028.png
    - assets/sticker/mugsy/tile029.png
    - assets/sticker/mugsy/tile030.png
    - assets/sticker/mugsy/tile031.png
    - assets/sticker/mugsy/tile032.png
    - assets/sticker/mugsy/tile033.png
    - assets/sticker/mugsy/tile034.png
    - assets/sticker/mugsy/tile035.png
    - assets/sticker/mugsy/tile036.png
    - assets/sticker/mugsy/tile037.png
    - assets/sticker/mugsy/tile038.png
    - assets/sticker/mugsy/tile039.png
    - assets/sticker/piyomaru/tile000.png
    - assets/sticker/piyomaru/tile001.png
    - assets/sticker/piyomaru/tile002.png
    - assets/sticker/piyomaru/tile003.png
    - assets/sticker/piyomaru/tile004.png
    - assets/sticker/piyomaru/tile005.png
    - assets/sticker/piyomaru/tile006.png
    - assets/sticker/piyomaru/tile007.png
    - assets/sticker/piyomaru/tile008.png
    - assets/sticker/piyomaru/tile009.png
    - assets/sticker/piyomaru/tile010.png
    - assets/sticker/piyomaru/tile011.png
    - assets/sticker/piyomaru/tile012.png
    - assets/sticker/piyomaru/tile013.png
    - assets/sticker/piyomaru/tile014.png
    - assets/sticker/piyomaru/tile015.png
    - assets/sticker/piyomaru/tile016.png
    - assets/sticker/piyomaru/tile017.png
    - assets/sticker/piyomaru/tile018.png
    - assets/sticker/piyomaru/tile019.png
    - assets/sticker/piyomaru/tile020.png
    - assets/sticker/piyomaru/tile021.png
    - assets/sticker/piyomaru/tile022.png
    - assets/sticker/piyomaru/tile023.png
    - assets/sticker/qoobee/tile000.png
    - assets/sticker/qoobee/tile001.png
    - assets/sticker/qoobee/tile002.png
    - assets/sticker/qoobee/tile003.png
    - assets/sticker/qoobee/tile004.png
    - assets/sticker/qoobee/tile005.png
    - assets/sticker/qoobee/tile006.png
    - assets/sticker/qoobee/tile007.png
    - assets/sticker/qoobee/tile008.png
    - assets/sticker/qoobee/tile009.png
    - assets/sticker/qoobee/tile010.png
    - assets/sticker/qoobee/tile011.png
    - assets/sticker/qoobee/tile012.png
    - assets/sticker/qoobee/tile013.png
    - assets/sticker/qoobee/tile014.png
    - assets/sticker/qoobee/tile015.png
    - assets/sticker/qoobee/tile016.png
    - assets/sticker/qoobee/tile017.png
    - assets/sticker/qoobee/tile018.png
    - assets/sticker/qoobee/tile019.png
    - assets/sticker/tonton2/tile000.png
    - assets/sticker/tonton2/tile001.png
    - assets/sticker/tonton2/tile002.png
    - assets/sticker/tonton2/tile003.png
    - assets/sticker/tonton2/tile004.png
    - assets/sticker/tonton2/tile005.png
    - assets/sticker/tonton2/tile006.png
    - assets/sticker/tonton2/tile007.png
    - assets/sticker/tonton2/tile008.png
    - assets/sticker/tonton2/tile009.png
    - assets/sticker/tonton2/tile010.png
    - assets/sticker/tonton2/tile011.png
    - assets/sticker/tonton2/tile012.png
    - assets/sticker/tonton2/tile013.png
    - assets/sticker/tonton2/tile014.png
    - assets/sticker/tonton2/tile015.png
    - assets/sticker/tonton2/tile016.png
    - assets/sticker/tonton2/tile017.png
    - assets/sticker/tonton2/tile018.png
    - assets/sticker/tonton2/tile019.png
    - assets/sticker/tonton2/tile020.png
    - assets/sticker/tonton2/tile021.png
    - assets/sticker/tonton2/tile022.png
    - assets/sticker/tonton2/tile023.png
    - assets/sticker/usagyuuun/tile000.png
    - assets/sticker/usagyuuun/tile001.png
    - assets/sticker/usagyuuun/tile002.png
    - assets/sticker/usagyuuun/tile003.png
    - assets/sticker/usagyuuun/tile004.png
    - assets/sticker/usagyuuun/tile005.png
    - assets/sticker/usagyuuun/tile006.png
    - assets/sticker/usagyuuun/tile007.png
    - assets/sticker/usagyuuun/tile008.png
    - assets/sticker/usagyuuun/tile009.png
    - assets/sticker/usagyuuun/tile010.png
    - assets/sticker/usagyuuun/tile011.png
    - assets/sticker/usagyuuun/tile012.png
    - assets/sticker/usagyuuun/tile013.png
    - assets/sticker/usagyuuun/tile014.png
    - assets/sticker/usagyuuun/tile015.png
    - assets/sticker/usagyuuun/tile016.png
    - assets/sticker/usagyuuun/tile017.png
    - assets/sticker/usagyuuun/tile018.png
    - assets/sticker/usagyuuun/tile019.png
    - assets/sticker/usagyuuun/tile020.png
    - assets/sticker/usagyuuun/tile021.png
    - assets/sticker/usagyuuun/tile022.png
    - assets/sticker/usagyuuun/tile023.png
    - assets/sticker/yam/tile000.png
    - assets/sticker/yam/tile001.png
    - assets/sticker/yam/tile002.png
    - assets/sticker/yam/tile003.png
    - assets/sticker/yam/tile004.png
    - assets/sticker/yam/tile005.png
    - assets/sticker/yam/tile006.png
    - assets/sticker/yam/tile007.png
    - assets/sticker/yam/tile008.png
    - assets/sticker/yam/tile009.png
    - assets/sticker/yam/tile010.png
    - assets/sticker/yam/tile011.png
    - assets/sticker/yam/tile012.png
    - assets/sticker/yam/tile013.png
    - assets/sticker/yam/tile014.png
    - assets/sticker/yam/tile015.png
    - assets/sticker/yam/tile016.png
    - assets/sticker/yam/tile017.png
    - assets/sticker/yam/tile018.png
    - assets/sticker/yam/tile019.png
    - assets/sticker/yam/tile020.png
    - assets/sticker/yam/tile021.png
    - assets/sticker/yam/tile022.png
    - assets/sticker/yam/tile023.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mono
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
          weight: 100
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
